name: Build latest PDF

on:
  push:
    branches:
      # PRs can only use caches from their target branch. We therefore need to
      # make sure we run on 'main' too.
      - main
      - dev
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  style:
    name: Build latest PDF
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v6

      - name: Cache TikZ externalized pictures
        uses: actions/cache@v5
        with:
          path: tex/figures/externalized
          key: tikz-externalized

       # First run of lualatex.
      - name: First lualatex FormalLanguageConstrainedReachabilityLectureNotes
        uses: dante-ev/latex-action@latest
        with:
          working_directory: tex
          root_file: FormalLanguageConstrainedReachabilityLectureNotes.tex
          compiler: lualatex
          args: -interaction=nonstopmode -shell-escape

      # Bibliography generation
      - name: bibtex FormalLanguageConstrainedReachabilityLectureNotes
        uses: dante-ev/latex-action@latest
        with:
          working_directory: tex
          root_file: FormalLanguageConstrainedReachabilityLectureNotes.aux
          compiler: bibtex
          args:

      # Second compilation
      - name: Second lualatex FormalLanguageConstrainedReachabilityLectureNotes
        uses: dante-ev/latex-action@latest
        with:
          working_directory: tex
          root_file: FormalLanguageConstrainedReachabilityLectureNotes.tex
          compiler: lualatex
          args: -interaction=nonstopmode -shell-escape

      # Final compilation
      - name: Final lualatex FormalLanguageConstrainedReachabilityLectureNotes
        uses: dante-ev/latex-action@latest
        with:
          working_directory: tex
          root_file: FormalLanguageConstrainedReachabilityLectureNotes.tex
          compiler: lualatex
          args: -interaction=nonstopmode -shell-escape

      - name: Get short SHA for commit
        id: sha_short
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Upload PDF file
        uses: actions/upload-artifact@v7
        with:
          name: FormalLanguageConstrainedReachabilityLectureNotes_${{ steps.sha_short.outputs.sha_short }}
          path: tex/FormalLanguageConstrainedReachabilityLectureNotes.pdf
