name: Build latest PDF

on:
  push:
    branches:
      # PRs can only use caches from their target branch. We therefore need to
      # make sure we run on 'main' too.
      - main
      - dev
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  style:
    name: Build latest PDF
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v6

      - name: Cache TikZ externalized pictures
        uses: actions/cache@v5
        with:
          path: tex/figures/externalized
          key: tikz-externalized

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v4
        with:
          root_file: tex/FormalLanguageConstrainedReachabilityLectureNotes.tex
          work_in_root_file_dir: true
          latexmk_use_lualatex: true
          extra_system_packages: "font-liberation"
          latexmk_shell_escape: true

      - name: Get short SHA for commit
        id: sha_short
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Upload PDF file
        uses: actions/upload-artifact@v7
        with:
          name: FormalLanguageConstrainedReachabilityLectureNotes_${{ steps.sha_short.outputs.sha_short }}
          path: tex/FormalLanguageConstrainedReachabilityLectureNotes.pdf
